# Generated by Django 3.2.5 on 2021-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tasks',
            field=models.CharField(max_length=200),
        ),
    ]
