# Generated by Django 3.2.5 on 2021-11-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20211023_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=200)),
                ('done', models.IntegerField(default=0)),
                ('date', models.IntegerField(default=0)),
            ],
        ),
    ]
