# Generated by Django 3.2.5 on 2021-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_progress_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chartcolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='red', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
